/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatarataRouteImport } from './routes/catarata'
import { Route as CienciaEEnsinoRouteImport } from './routes/ciencia-e-ensino'
import { Route as CirurgiaRefrativaRouteImport } from './routes/cirurgia-refrativa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CorneaRouteImport } from './routes/cornea'
import { Route as DraDianeRouteImport } from './routes/dra-diane'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as DraDianeExplicaIndexRouteImport } from './routes/dra-diane-explica.index'
import { Route as DraDianeExplicaSlugRouteImport } from './routes/dra-diane-explica.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatarataRoute = CatarataRouteImport.update({
  id: '/catarata',
  path: '/catarata',
  getParentRoute: () => rootRouteImport,
} as any)
const CienciaEEnsinoRoute = CienciaEEnsinoRouteImport.update({
  id: '/ciencia-e-ensino',
  path: '/ciencia-e-ensino',
  getParentRoute: () => rootRouteImport,
} as any)
const CirurgiaRefrativaRoute = CirurgiaRefrativaRouteImport.update({
  id: '/cirurgia-refrativa',
  path: '/cirurgia-refrativa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CorneaRoute = CorneaRouteImport.update({
  id: '/cornea',
  path: '/cornea',
  getParentRoute: () => rootRouteImport,
} as any)
const DraDianeRoute = DraDianeRouteImport.update({
  id: '/dra-diane',
  path: '/dra-diane',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const DraDianeExplicaIndexRoute = DraDianeExplicaIndexRouteImport.update({
  id: '/dra-diane-explica/',
  path: '/dra-diane-explica/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraDianeExplicaSlugRoute = DraDianeExplicaSlugRouteImport.update({
  id: '/dra-diane-explica/$slug',
  path: '/dra-diane-explica/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catarata': typeof CatarataRoute
  '/ciencia-e-ensino': typeof CienciaEEnsinoRoute
  '/cirurgia-refrativa': typeof CirurgiaRefrativaRoute
  '/contato': typeof ContatoRoute
  '/cornea': typeof CorneaRoute
  '/dra-diane': typeof DraDianeRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/dra-diane-explica/$slug': typeof DraDianeExplicaSlugRoute
  '/dra-diane-explica/': typeof DraDianeExplicaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catarata': typeof CatarataRoute
  '/ciencia-e-ensino': typeof CienciaEEnsinoRoute
  '/cirurgia-refrativa': typeof CirurgiaRefrativaRoute
  '/contato': typeof ContatoRoute
  '/cornea': typeof CorneaRoute
  '/dra-diane': typeof DraDianeRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/dra-diane-explica/$slug': typeof DraDianeExplicaSlugRoute
  '/dra-diane-explica': typeof DraDianeExplicaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catarata': typeof CatarataRoute
  '/ciencia-e-ensino': typeof CienciaEEnsinoRoute
  '/cirurgia-refrativa': typeof CirurgiaRefrativaRoute
  '/contato': typeof ContatoRoute
  '/cornea': typeof CorneaRoute
  '/dra-diane': typeof DraDianeRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/dra-diane-explica/$slug': typeof DraDianeExplicaSlugRoute
  '/dra-diane-explica/': typeof DraDianeExplicaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catarata'
    | '/ciencia-e-ensino'
    | '/cirurgia-refrativa'
    | '/contato'
    | '/cornea'
    | '/dra-diane'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/dra-diane-explica/$slug'
    | '/dra-diane-explica/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catarata'
    | '/ciencia-e-ensino'
    | '/cirurgia-refrativa'
    | '/contato'
    | '/cornea'
    | '/dra-diane'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/dra-diane-explica/$slug'
    | '/dra-diane-explica'
  id:
    | '__root__'
    | '/'
    | '/catarata'
    | '/ciencia-e-ensino'
    | '/cirurgia-refrativa'
    | '/contato'
    | '/cornea'
    | '/dra-diane'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/dra-diane-explica/$slug'
    | '/dra-diane-explica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatarataRoute: typeof CatarataRoute
  CienciaEEnsinoRoute: typeof CienciaEEnsinoRoute
  CirurgiaRefrativaRoute: typeof CirurgiaRefrativaRoute
  ContatoRoute: typeof ContatoRoute
  CorneaRoute: typeof CorneaRoute
  DraDianeRoute: typeof DraDianeRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  DraDianeExplicaSlugRoute: typeof DraDianeExplicaSlugRoute
  DraDianeExplicaIndexRoute: typeof DraDianeExplicaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catarata': {
      id: '/catarata'
      path: '/catarata'
      fullPath: '/catarata'
      preLoaderRoute: typeof CatarataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciencia-e-ensino': {
      id: '/ciencia-e-ensino'
      path: '/ciencia-e-ensino'
      fullPath: '/ciencia-e-ensino'
      preLoaderRoute: typeof CienciaEEnsinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cirurgia-refrativa': {
      id: '/cirurgia-refrativa'
      path: '/cirurgia-refrativa'
      fullPath: '/cirurgia-refrativa'
      preLoaderRoute: typeof CirurgiaRefrativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cornea': {
      id: '/cornea'
      path: '/cornea'
      fullPath: '/cornea'
      preLoaderRoute: typeof CorneaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dra-diane': {
      id: '/dra-diane'
      path: '/dra-diane'
      fullPath: '/dra-diane'
      preLoaderRoute: typeof DraDianeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dra-diane-explica/': {
      id: '/dra-diane-explica/'
      path: '/dra-diane-explica'
      fullPath: '/dra-diane-explica/'
      preLoaderRoute: typeof DraDianeExplicaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dra-diane-explica/$slug': {
      id: '/dra-diane-explica/$slug'
      path: '/dra-diane-explica/$slug'
      fullPath: '/dra-diane-explica/$slug'
      preLoaderRoute: typeof DraDianeExplicaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatarataRoute: CatarataRoute,
  CienciaEEnsinoRoute: CienciaEEnsinoRoute,
  CirurgiaRefrativaRoute: CirurgiaRefrativaRoute,
  ContatoRoute: ContatoRoute,
  CorneaRoute: CorneaRoute,
  DraDianeRoute: DraDianeRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  DraDianeExplicaSlugRoute: DraDianeExplicaSlugRoute,
  DraDianeExplicaIndexRoute: DraDianeExplicaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
